travel-guide-tw/travel-guide-tw.github.io

.github/labeler.yml, .github/workflows/docs.yml
=> fix(labeler): fix path

.github/workflows/docs_test.yml
=> ci(vuepress): test vuepress doc build on PR

docs/.vuepress/config.ts
=> fix(vuepress): fix sidebar links

.github/labeler.yml, .github/workflows/action.yml, .github/workflows/labeler.yml, .prettierrc, docs/.vuepress/config.ts
=> style(prettier): add rule "semi": false & "singleQuote": true

.gitignore, docs/.vuepress/config.ts, package-lock.json, package.json
=> feat(ga): add g tag

README.md, docs/.vuepress/config.ts, package-lock.json, package.json
=> chore(github): migrate to travel-guide-tw organization

.github/workflows/docs.yml
=> build(env): use github secret for env

docs/.vuepress/config.ts
=> chore(google-console): add meta in head

docs/.vuepress/config.ts
=> fix(google-console): use env for the content

docs/.vuepress/config.ts
=> fix(vuepress): fix property repo location

docs/.vuepress/styles/index.scss
iframe size tyle only works to google map
- iframe size tyle only works to google map
=> feat(styles): iframe size tyle only works to google map

docs/.vuepress/config.ts, package-lock.json, package.json
=> feat(sitemap): use sitemap plugin

docs/.vitepress/components/GiscusWrapper.vue
=> fix(giscus): rerender after route change

docs/.vitepress/components/GiscusWrapper.vue
fix resize after rerendering
...
add host
- ...
https://github.com/giscus/giscus-component/issues/1003
- ...
=> fix(giscus): fix resize after rerendering

docs/.vitepress/components/GiscusWrapper.vue, docs/.vitepress/config.ts
=> feat(giscus): adjust title for giscus

docs/.vitepress/config.ts
Reverts travel-guide-tw/travel-guide-tw.github.io#51
=> Revert "feat(vitepress): add target: '_self',"

docs/.vitepress/config.ts, docs/.vitepress/typescript/node/searchPlugin.ts, package-lock.json, package.json
=> feat(search): init search

docs/.vitepress/config.ts
as title
- ...
- https://github.com/emersonbottero/vitepress-plugin-search/issues/58
=> fix(search): set build ssr to false to fix search

.vitepress/typescript/node/generateRewrites.ts, .vitepress/typescript/node/generateSidebar.ts, .vitepress/typescript/node/getFilePaths.ts, package-lock.json, package.json, tsconfig.json
=> fix(glob): update glob and fix file paths

.github/workflows/prettier.yml
prevent running creyD/prettier_action@v4.3 on PR
- remove `pull_request:` in prettier github action
- https://github.com/creyD/prettier_action/issues/54
=> fix(github-action): prevent running creyD/prettier_action@v4.3 on PR

docs/台灣/基隆/景點/和平島公園.md, docs/台灣/基隆/景點/國立海洋科學博物館.md, docs/台灣/基隆/景點/潮境公園.md, docs/台灣/基隆/景點/潮境智能海洋館.md
新增臺灣基隆景點
新增以下檔案
```
docs/台灣/基隆/景點/和平島公園.md
docs/台灣/基隆/景點/國立海洋科學博物館.md
docs/台灣/基隆/景點/潮境公園.md
docs/台灣/基隆/景點/潮境公園.md
docs/台灣/基隆/景點/潮境智能海洋館.md
```
- [和平島地質公園](https://www.hpigeopark.org/hours-admission)
- [國立海洋科學博物館](https://www.nmmst.gov.tw/chhtml/)
- [中華民國交通部觀光局 國立海洋科學博物館](https://www.taiwan.net.tw/m1.aspx?sNo=0001105&id=A12-00221)
- [中華民國交通部觀光局 潮境公園](https://www.taiwan.net.tw/m1.aspx?sNo=0001016&id=A12-00359)
- [潮境智能海洋館](https://iocean.nmmst.gov.tw/)
=> feat(keelung): add tourist attractions in keelung

.vitepress/config.ts, package-lock.json, package.json
close #65
support checkboxes
- add `markdown-it-task-lists`
- https://www.npmjs.com/package/markdown-it-task-lists
=> feat(markdown): support checkboxes

.vitepress/components/GiscusWrapper.vue, .vitepress/config.ts, package-lock.json, package.json
migrate to rc version
- update vitepress
- use vitepress sitemap feature
- fix related issue
- ...
=> chore(vitepress): migrate to rc version

docs/日本/_其他/櫻花花況網站.md
Add Sakura site links
- 櫻花花況網站
-  同修改內容連結
=> feat(japan): add sakura site links

.vitepress/config.ts, .vitepress/typescript/node/gtagHead.ts, package-lock.json, package.json
=> chore(package): update vitepress to 1.2.3

docs/日本/_注意事項/入境相關規定.md
remove covid-19 related info
- remove covid-19 related info
=> feat(japan-entrance): remove covid-19 related info

.vitepress/config.ts, .vitepress/styles/iframe.scss, .vitepress/styles/index.scss, .vitepress/styles/linkPreview.scss, docs/index.md, package-lock.json, package.json
add markdown it preview link plugin
use this to create preview link
``` md
[@preview](https://github.com/travel-guide-tw/travel-guide-tw.github.io)
```
- add markdown it preview link plugin
- https://github.com/junkawa/markdown-it-link-preview
=> feat(markdown): add markdown it preview link plugin

docs/日本/山梨/活動/攀登富士山.md
subaru line access
- ...
- [富士急行 富士五湖～新宿線](https://bus.fujikyu.co.jp/highway/detail/id/1)
- [路線バス　富士スバルライン五合目線](https://www.fujikyubus.co.jp/pdf/rosen/detail_id14_timetable_20240405.pdf)
=> feat(fujiyama): subaru line access

.github/workflows/docs.yml, .vitepress/typescript/node/generateSidebar.ts, CONTRIBUTING.md
adjust contributing text and copy the file before building
- adjust contributing text
- copy the file before building
- fix type error
=> feat(contributing): adjust contributing text and copy the file before building

.vitepress/config.ts
set lang to zh-Hant-TW
- set lang to zh-Hant-TW
- https://datatracker.ietf.org/doc/html/rfc5646
=> feat(config): set lang to zh-Hant-TW

.github/workflows/docs.yml, .github/workflows/docs_test.yml, .github/workflows/format.yml, .vitepress/config.ts, .vitepress/typescript/node/generateRewrites.ts, .vitepress/typescript/node/generateSidebar.ts
add the contribute page on config instead of copying it before building
=> feat(vitepress): add hte contribute page on config instead of copying it before building

docs/public/robots.txt
add robots.txt file
- add `robots.txt` file
- no content update
=> chore(robots): add `robots.txt` file

docs/index.md
change the key Visual Design image that ChatGPT creates
=> feat: change key Visual Design image

.vitepress/config.ts
set markdown.image.lazyLoading to true
- https://vitepress.dev/guide/markdown#image-lazy-loading
=> feat: Update config.ts

docs/index.md
resize the main image to 688*688
resize the main image to 688*688
=> feat: resize the main image to 688*688

.vitepress/config.ts, package-lock.json, package.json
add og meta head generator
- install cheerio
- add transformHead setting
- https://vitepress.dev/reference/site-config#transformhead
=> feat(config): add og meta head generator

.vitepress/config.ts
add og site name
- https://developers.google.com/search/docs/appearance/site-names?hl=zh-tw#website
=> feat(config): add og site name

.vitepress/config.ts, .vitepress/styles/index.scss, LICENSE, package.json
adjust license and add footer with license
- use Apache 2.0
- add footer with CC BY-NC 4.0
=> feat(copy-right): adjust license and add footer with license

.vitepress/styles/index.scss
use `@use` instead of `@import`
=> fix(scss): use `@use` instead of `@import`

.github/workflows/docs.yml, .github/workflows/docs_test.yml, .github/workflows/format.yml, .vitepress/config.ts, docs/日本/東京/_交通/機場.md, package-lock.json, package.json
init mermaid
- install an init vitepress-plugin-mermaid
- add example code
=> feat(mermaid): init with vitepress
